### ISSUE TITLE
Дубликат репозитория

### ISSUE THREAD

**Issue by bearpro** [rtu-mirea/laboratornaya-rabota-4-znakomstvo-s-prolog-BearPro-1#1]
Случайно зарегался дважды. У меня прав управления репозиторием нет, по этому удалить не могу (или не могу найти *как*).

**Comment by madskills700** [comment]
заливай в репу с цифрой 1, другую я удалю, когда найду, в какую группу ты зашел сначала.

**Comment by bearpro** [comment]
> 
> заливай в репу с цифрой 1, другую я удалю, когда найду, в какую группу ты зашел сначала.

Я уже залил всё ту, которую создал раньше: https://github.com/rtu-mirea/laboratornaya-rabota-4-znakomstvo-s-prolog-BearPro

**Comment by madskills700** [comment]
нашел, в 11 группе потусишь на 4 лабе 🌚

**Comment by bearpro** [comment]
Я вообще не замечал что тут деление на группы. 
Этот репозиторий в удалённые добавил, так что можно удалять любой.

**Comment by madskills700** [comment]
это, эту репу могут потом смотреть) я понимаю отношение к этому всему, но, пожалуйста, чуть более формально репозиторий отрихтуй) спойлер я уже форспушем убрал 🌚 ну и зачел работу, естественно. Правда в чем соль работы я тоже не совсем понял.

**Comment by bearpro** [comment]
Да вроде больше ничего неформального нет.

**Comment by madskills700** [comment]
Ну все, огонь. Это, не для остальных информация, но кого зеленым отметил, я попробую топить за автоматы людям, так что мб как-то облегчу нескольким людям жизнь.Пока список не полный, да и я не все еще проверил.--Отправлено из мобильной Яндекс.Почты28.12.2019, 11:26, "Михаил Проказин" <notifications@github.com>:Да вроде больше ничего неформального нет.
